import { FileText, Printer } from '../../components/icons'
import { useAppStore } from '../../store/useAppStore'
import { useProjection } from '../../lib/useProjection'
import { treatmentById } from '../../data/evidence'
import { metricLabels } from '../../lib/labels'
import type { MetricKey } from '../../lib/types'
import { GlassCard, SectionTitle } from '../../components/ui'

const DOCTOR_QUESTIONS = [
  'Is the current risperidone dose still the best risk-benefit fit?',
  'Are weight, appetite, sleep, prolactin, movement side effects, and metabolic markers being monitored?',
  'Is NAC (or any supplement we are considering) appropriate with this medication profile?',
  'Are there seizure, asthma, liver, kidney, bleeding, or medication-interaction concerns?',
  'Which behaviour target are we actually trying to improve?',
  'How will we measure success after 8 to 12 weeks?',
]

export function DoctorPack() {
  const { selectedAdjuncts, risperidoneDose, nacDose, baselineMetrics } = useAppStore()
  const projection = useProjection()
  const considering = [
    ...(nacDose > 0 ? ['nac'] : []),
    ...selectedAdjuncts,
  ]
    .map((id) => treatmentById(id))
    .filter(Boolean)

  return (
    <GlassCard>
      <SectionTitle
        icon={<FileText size={20} />}
        title="Doctor Visit Pack"
        subtitle="A clean one-page summary to take to the appointment. Print it or save as PDF from the print dialog."
      />
      <button onClick={() => window.print()} className="btn-primary mb-4 text-sm">
        <Printer size={16} /> Print / save as PDF
      </button>

      <div id="doctor-pack" className="overflow-hidden rounded-xl bg-white p-6 text-sm text-slate-700 ring-1 ring-brand-deep/12">
        <div
          className="-m-6 mb-6 flex items-center gap-3 p-5 text-white"
          style={{ background: 'linear-gradient(110deg, #0E5196, #1740A8)' }}
        >
          <img src={`${import.meta.env.BASE_URL}brand/autism-compass-mark.svg`} alt="" className="h-9 w-9 rounded-lg bg-white/95 p-0.5" />
          <div>
            <h3 className="text-base font-black leading-none">Autism Compass — Doctor Visit Pack</h3>
            <p className="mt-1 text-[11px] text-white/75">Example profile · Education only, not medical advice</p>
          </div>
        </div>

        <section className="mt-4">
          <h4 className="font-extrabold text-brand-navy">Current medication reference</h4>
          <p>Risperidone {risperidoneDose} mg/day (reference only, not a recommendation).</p>
        </section>

        <section className="mt-3">
          <h4 className="font-extrabold text-brand-navy">Baseline behaviours (0 calm – 10 severe)</h4>
          <ul className="ml-4 list-disc">
            {(Object.keys(baselineMetrics) as MetricKey[])
              .filter((k) => baselineMetrics[k] >= 5)
              .map((k) => (
                <li key={k}>
                  {metricLabels[k]}: {baselineMetrics[k]}
                </li>
              ))}
          </ul>
        </section>

        {considering.length > 0 && (
          <section className="mt-3">
            <h4 className="font-extrabold text-brand-navy">Options we want to discuss</h4>
            <ul className="ml-4 list-disc">
              {considering.map((t) => (
                <li key={t!.id}>
                  <span className="font-bold">{t!.name}</span> — {t!.evidenceLevel} evidence.{' '}
                  {t!.doctorOnly ? 'Doctor-only item. ' : ''}
                  {t!.confidenceNote}
                </li>
              ))}
            </ul>
          </section>
        )}

        <section className="mt-3">
          <h4 className="font-extrabold text-brand-navy">What the model estimated (not a promise)</h4>
          <ul className="ml-4 list-disc">
            {(Object.keys(projection) as MetricKey[])
              .filter((k) => Math.abs(projection[k].projected - projection[k].baseline) >= 0.5)
              .map((k) => (
                <li key={k}>
                  {metricLabels[k]}: {projection[k].baseline} → {projection[k].projected}
                </li>
              ))}
          </ul>
        </section>

        <section className="mt-3">
          <h4 className="font-extrabold text-brand-navy">Questions for the team</h4>
          <ul className="ml-4 list-disc">
            {DOCTOR_QUESTIONS.map((q) => (
              <li key={q}>{q}</li>
            ))}
          </ul>
        </section>

        <p className="mt-4 border-t border-slate-200 pt-2 text-xs text-slate-400">
          Generated by AutismCompass. Education only. Not medical advice. Do not change medication
          without the prescriber.
        </p>
      </div>
    </GlassCard>
  )
}
